spring:
  datasource:
    url: jdbc:h2:file:./data/app_db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true # to enable h2 console
app:
  config:
    drawerAmount: 3